In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
df.bedrooms.median()

4.0

In [4]:
#Taking integer values 
import math
median_badrooms = math.floor(df.bedrooms.median())
median_badrooms

4

In [5]:
#Fill all NAN values with this median number
df.bedrooms = df.bedrooms.fillna(median_badrooms)
df.bedrooms

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
X = df[['area','bedrooms','age']]
X

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [8]:
y = df.price
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [9]:
reg = linear_model.LinearRegression()
reg.fit(X.values,y)

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540443

For our dataset, our equation is price = m1 x area + m2 x bedrooms + m3 x age + b

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [14]:
result = (112.06244194*3000) + (23388.88007794*3) + (-3231.71790863*40) + (221323.00186540443)
result

498408.25157402444

In [15]:
reg.predict([[2500,4,5]])

array([578876.03748933])