In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience = df.experience.fillna('one')
df.experience

0       one
1       one
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [4]:
median_test_score = df['test_score(out of 10)'].median()
median_test_score

8.0

In [5]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

In [6]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        one                    8.0                           9      50000
1        one                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

If "module is not found" error showed without any problem then run the cell below 👇

In [7]:
# import sys  
# !{sys.executable} -m pip install --user word2number

In [8]:
from word2number import w2n

In [9]:
#df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x))
df['experience'] = df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [10]:
X = df[['experience','test_score(out of 10)','interview_score(out of 10)']]
X.head()

experience  test_score(out of 10)  interview_score(out of 10)
0           1                    8.0                           9
1           1                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6

In [11]:
y = df['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [12]:
reg = linear_model.LinearRegression()
reg.fit(X.values,y)

LinearRegression()

In [13]:
reg.coef_

array([3031.1979513 , 1893.22650937, 2485.73083785])

In [14]:
reg.intercept_

13359.721134159729

In [15]:
reg.predict([[2,9,6]])

array([51375.54064819])

In [16]:
result = 3031.1979513*2 + 1893.22650937*9 + 2485.73083785*6 + 13359.721134159729
result

51375.54064818973

In [17]:
reg.predict([[12,10,10]])

array([93523.67002192])